export default function handler(req, res) {
    if (req.method !== 'POST') {
      return res.status(405).json({ message: 'Method not allowed' });
    }
    
    const { message, contextInfo } = req.body;
    
    res.status(200).json({
      message: {
        role: 'coach',
        content: `I received your message: "${message}". This is a mock response since we're in development mode. In production, this would be generated by an AI coach based on your specific question and the current context.`,
        timestamp: new Date().toISOString()
      }
    });
  }